#!/usr/bin/env python3
"""
Match the original fn_opt_levels_1x.txt hot function entries against
the actual def_path_str function names from a build's unmatched log.

Strips monomorphization, lifetimes, brackets to find the best match.
Outputs a new fn file using the CORRECT def_path_str names.
"""
import re
import sys
from collections import defaultdict

def normalize_for_match(s):
    """Aggressively normalize to match equivalent functions."""
    s = s.strip()
    # Strip lifetime annotations entirely
    s = re.sub(r"'(?:[a-zA-Z_][a-zA-Z0-9_]*|_)", "", s)
    s = s.replace("<>", "")
    # Remove empty <> that may remain (e.g. after lifetime removal)
    while "<>" in s:
        s = s.replace("<>", "")
    # Strip leading < and trailing >::  for inherent impls
    # <Type>::method or <crate::Type>::method -> Type::method or crate::Type::method
    if " as " not in s and s.startswith("<") and ">::" in s:
        s = s[s.index("<")+1:]
        s = s.replace(">::", "::", 1)
    # Strip trailing ::<ConcreteType> monomorphization params
    s = re.sub(r"::<[^>]*>$", "", s)
    # Also strip ::<...>::<...> (nested turbofish at end)
    while re.search(r"::<[^>]*>$", s):
        s = re.sub(r"::<[^>]*>$", "", s)
    # Collapse multiple colons
    while "::::" in s:
        s = s.replace("::::", "::")
    # Remove crate doubled prefix: crate::crate::mod::fn -> crate::mod::fn
    parts = s.split("::")
    if len(parts) >= 3 and parts[0] == parts[1]:
        s = "::".join(parts[1:])
    return s

def main():
    fn_file = sys.argv[1] if len(sys.argv) > 1 else \
        "/root/src/rustloop/rust1.96/build/pgo_data/fn_opt_levels_1x.txt"
    unmatched_log = sys.argv[2] if len(sys.argv) > 2 else \
        "/root/src/rustloop/rust1.96/build/pgo_data/fn_opt_levels_1x.fn_opt_levels.unmatched.log"
    output = sys.argv[3] if len(sys.argv) > 3 else \
        "/root/src/rustloop/rust1.96/build/pgo_data/fn_opt_levels_1x_matched.txt"

    # Read all def_path_str function names from the unmatched log
    # (both "fn defaulting:" and "entry unmatched:" lines contain valid fn names)
    def_path_entries = {}  # normalized -> (original_name, opt_level_or_NONE)
    matched_opt = {}       # original_name -> opt_level (from entry unmatched lines)
    
    with open(unmatched_log) as f:
        for line in f:
            m = re.match(r'fn defaulting: (.+) (O[3s2z])', line)
            if m:
                name, opt = m.group(1), m.group(2)
                norm = normalize_for_match(name)
                if norm not in def_path_entries:
                    def_path_entries[norm] = (name, opt)
    
    print(f"Read {len(def_path_entries)} unique normalized function names from build", file=sys.stderr)

    # Read fn file entries
    fn_hot = []
    with open(fn_file) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            parts = line.rsplit(' ', 1)
            if len(parts) == 2:
                fn_hot.append((parts[0], parts[1]))

    print(f"Read {len(fn_hot)} hot function entries from {fn_file}", file=sys.stderr)

    # Match each hot function against build names
    matched = []
    unmatched = []
    for fn_name, opt_level in fn_hot:
        norm = normalize_for_match(fn_name)
        if norm in def_path_entries:
            actual_name, _ = def_path_entries[norm]
            matched.append((actual_name, opt_level))
        else:
            unmatched.append((fn_name, opt_level))

    print(f"\nMatched: {len(matched)}/{len(fn_hot)} ({len(matched)*100/len(fn_hot):.1f}%)", file=sys.stderr)
    print(f"Unmatched: {len(unmatched)}/{len(fn_hot)}", file=sys.stderr)

    # Write output
    with open(output, 'w') as f:
        f.write(f"# Matched fn_opt_levels generated by {__file__}\n")
        f.write(f"# Source: {fn_file}\n")
        f.write(f"# Build names from: {unmatched_log}\n")
        f.write(f"# Match rate: {len(matched)}/{len(fn_hot)} ({len(matched)*100/len(fn_hot):.1f}%)\n")
        f.write("\n")
        for name, opt in sorted(matched):
            f.write(f"{name} {opt}\n")

    print(f"\nWrote {len(matched)} entries to {output}", file=sys.stderr)
    
    # Show by opt level
    from collections import Counter
    c = Counter(opt for _, opt in matched)
    print("By opt level:", dict(c), file=sys.stderr)

if __name__ == '__main__':
    main()
